#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
import argparse

# Import from cow
import cow
from cow.lib import say_hello

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'cow_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    parser.add_argument('-m', '--message', type=str, default='hello')
    args = parser.parse_args()
    say_hello(args.message)
